# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Builds release apk"
  lane :build do
    gradle(task: "clean test")
    gradle(task: "clean assembleRelease")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(
      track: 'internal',
      apk: 'app/build/outputs/apk/release/app-release.apk',
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Promote from to Production"
  lane :promote do
  supply(
    track: 'internal',
    track_promote_to: 'production',
    skip_upload_images: true,
    skip_upload_screenshots: true
  )
  end
end
