name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: |
          ls -la
          ls .. -la
          ls ../.. -la
          pwd
          chmod +x ../../ci.sh
      - uses: actions/checkout@v1
      - name: Gradle Command
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: testDebugUnitTest
