name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: |
        ./ci.sh
      - uses: actions/checkout@v1
      - name: Gradle Command
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: testDebugUnitTest
